[project]
name = "python-code-quality-assurance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Francisco Mendoza", email = "mentofran@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []


